fix to paymentservice. check commentbody
It is more hack to fix issue with pino which is dev dependency
which used in code and with a flag --only=production not installed

k logs paymentservice-dffcf8b6-zghv5
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module 'pino'
Require stack:
- /usr/src/app/logger.js
- /usr/src/app/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/usr/src/app/logger.js:17:14)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/src/app/logger.js', '/usr/src/app/index.js' ]
}

Node.js v20.15.1